---

services:
- service: deadbeef-aaaa-bbbb-cccc-000000000001
  module: examples.multi_agent_adapter.document_summarizer.DocumentSummarizer
  required_services:
  - id: deadbeef-aaaa-bbbb-cccc-000000000002
    agents:
    - b545478a-971a-cccc-bc56-bbbbbbbbbbbb

  - id: deadbeef-aaaa-bbbb-cccc-000000000003
    agents:
    - b545478a-971a-cccc-bc56-bbbbbbbbbbbb

  - id: deadbeef-aaaa-bbbb-cccc-000000000004
    agents:
    - 804be272-1cd8-4e11-8e5d-2eed03d47405
  - id: deadbeef-aaaa-bbbb-cccc-000000000005
    agents:
    - 804be272-1cd8-4e11-8e5d-2eed03d47405
  - id: deadbeef-aaaa-bbbb-cccc-000000000006
    agents:
    - 804be272-1cd8-4e11-8e5d-2eed03d47405

- service: deadbeef-aaaa-bbbb-cccc-000000000101
  module: examples.simple_adapter.SimpleAdapter

- service: deadbeef-aaaa-bbbb-cccc-111111111101
  module: adapters.tensorflow.mnist.TensorflowMNIST

- service: deadbeef-aaaa-bbbb-cccc-000000000202
  module: adapters.opencog.relex.RelexAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000002
  module: adapters.aigents.AigentsTextsClustererAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000003
  module: adapters.aigents.AigentsTextExtractorAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000004
  module: adapters.aigents.AigentsSocialGrapherAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000005
  module: adapters.aigents.AigentsRSSFeederAdapter


